# Generated by Django 4.2.16 on 2024-12-09 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('product_id', models.IntegerField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=255, unique=True)),
                ('image_url', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='review',
            fields=[
                ('review_id', models.IntegerField(primary_key=True, serialize=False)),
                ('review_data', models.TextField()),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skincare.product')),
            ],
        ),
    ]
